# Generated by Django 4.2.7 on 2026-04-01 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('hours', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('whatsapp', models.URLField(blank=True)),
                ('success_rate', models.CharField(default='95%', max_length=10)),
                ('happy_customers', models.CharField(default='50,000+', max_length=20)),
                ('years_experience', models.CharField(default='10+', max_length=10)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Info',
                'verbose_name_plural': 'Site Info',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('size', models.CharField(blank=True, max_length=50)),
                ('features', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('product_type', models.CharField(choices=[('single', 'Single'), ('bundle', 'Bundle')], default='single', max_length=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='store.siteinfo')),
            ],
        ),
    ]
