# Generated by Django 4.2.12 on 2026-04-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_order_product_image_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
